# 3. Model Train + SHAP / FFA Analysis

**Purpose:** Run pipeline Steps 4–8: model data → PGx → final model → SHAP → FFA/DTW/FP-Growth.

**Flow:** Steps 4 (model data) → 5 (PGx enrichment) → 6 (final model) → 7 (SHAP) → 8 (FFA + DTW + FP-Growth).

**Steps:** Sync inputs → Verify → Step 4 (model data) → Step 5 (PGx) → Step 6 (final model) → Step 7 (SHAP) → Step 8 (FFA).

**Memory:** Pipeline scripts use **DuckDB and Parquet** where possible. Pandas only where required (model/SHAP APIs).

Prerequisites: Cohorts from `1_cohort_workflow.ipynb` (Step 2) and feature importance from `2_feature_importance.ipynb` plus any refined Step 3b feature lists. Run from repo root.

In [5]:
# Setup: paths and project root
import sys
import os
import subprocess
from pathlib import Path

PROJECT_ROOT = Path().resolve()
sys.path.insert(0, str(PROJECT_ROOT))

from py_helpers.env_utils import get_data_root
from py_helpers.workflow_sync_checkpoint import sync_s3_to_local, check_step_checkpoint_exists, save_step_checkpoint

S3_BUCKET = os.environ.get("CPIC_S3_BUCKET", "pgxdatalake")
DATA_ROOT = get_data_root()
AWS_PROFILE = os.environ.get("AWS_PROFILE")

print("CPIC Time-to-Event Analysis - Model + SHAP/FFA Workflow")
print("=" * 60)
print(f"Project root: {PROJECT_ROOT}")
print(f"Data root (NVMe/local): {DATA_ROOT}")
print("=" * 60)

CPIC Time-to-Event Analysis - Model + SHAP/FFA Workflow
============================================================
Project root: /home/pgx3874/cpic_time_to_event_analysis
Data root (NVMe/local): /mnt/nvme
============================================================

In [6]:
# Both cohorts use the same production age-band set: 65-74 and 75-84.
from py_helpers.constants import REQUIRED_COHORTS

# Input dirs
COHORTS_ROOT = DATA_ROOT / "gold" / "cohorts"
FI_ROOT = DATA_ROOT / "gold" / "feature_importance"
STEP3_OUTPUTS = STEP3B_OUTPUTS = FI_ROOT

from py_helpers.env_utils import get_model_data_root
MODEL_DATA_ROOT = get_model_data_root()

# Output dirs
FINAL_MODEL_OUTPUTS = PROJECT_ROOT / "6_final_model" / "outputs"
FINAL_MODEL_OUTPUTS_ALT = DATA_ROOT / "6_final_model" / "outputs"
FINAL_MODEL_GOLD = DATA_ROOT / "gold" / "final_model"

print("Cohorts and age bands:")
for cohort, bands in REQUIRED_COHORTS.items():
    print(f"  {cohort}: {bands}")
print("\nInput dirs (for Steps 4-6):")
print(f"  Cohorts (2):               {COHORTS_ROOT}")
print(f"  Feature importance (3/3b): {FI_ROOT}")
print(f"  Model data (4; in/out):    {MODEL_DATA_ROOT}")
print("\nOutput dirs (Step 6):")
print(f"  Project:   {FINAL_MODEL_OUTPUTS}")
print(f"  NVMe:      {FINAL_MODEL_OUTPUTS_ALT}")
print(f"  gold/NVMe: {FINAL_MODEL_GOLD}")

Cohorts and age bands:
  falls: ['65-74', '75-84']
  ed: ['65-74', '75-84']

Input dirs (for Steps 4-6):
  Cohorts (2):               /mnt/nvme/gold/cohorts
  Feature importance (3/3b): /mnt/nvme/gold/feature_importance
  Model data (4; in/out):    /mnt/nvme/cpic_time_to_event/4_model_data

Output dirs (Step 6):
  Project:   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs
  NVMe:      /mnt/nvme/6_final_model/outputs
  gold/NVMe: /mnt/nvme/gold/final_model

## Clear all checkpoints and pipeline outputs (optional - for a fresh run)

Run this cell **once** when you want to rebuild the full pipeline from Step 4 through SHAP/FFA. It (1) clears S3 checkpoints, (2) deletes S3 pipeline outputs so Steps 4 and 6 re-run instead of re-downloading, (3) removes local output directories.

**Safety confirmation required:** edit `CONFIRM_CLEAR_ALL` in the next cell to exactly `CLEAR STEP 4-8 OUTPUTS` before running. Leave it blank to skip. After this, run the Sync cell and then Steps 4 --> 5 --> 6 --> Step 7 --> Step 8.

In [ ]:
# Clear S3 checkpoints, S3 pipeline outputs, and local outputs for a fresh model + SHAP/FFA run.
# Safety: this cell deletes generated project artifacts. It will not run unless
# CONFIRM_CLEAR_ALL exactly matches REQUIRED_CONFIRMATION.
import logging
import shutil
import subprocess
from pathlib import Path

from py_helpers.workflow_sync_checkpoint import clear_step_checkpoints, delete_step_checkpoint

REQUIRED_CONFIRMATION = "CLEAR STEP 4-8 OUTPUTS"
CONFIRM_CLEAR_ALL = ""  # Type CLEAR STEP 4-8 OUTPUTS here to enable deletion.

if CONFIRM_CLEAR_ALL != REQUIRED_CONFIRMATION:
    print("Clear-all skipped.")
    print(f"To run, set CONFIRM_CLEAR_ALL = {REQUIRED_CONFIRMATION!r} and rerun this cell.")
else:
    logger = logging.getLogger(__name__)
    print("Confirmation accepted. Clearing generated Step 4-8 checkpoints and outputs...")

    # 1) S3 checkpoint metadata so steps don't think they're done
    for step in ("4_model_data", "6_final_model"):
        for cohort, bands in REQUIRED_COHORTS.items():
            n = clear_step_checkpoints(step, cohort, bands, logger=None)
            print(f"Cleared {n} checkpoint(s) for {step} / {cohort}")

    # 2) S3 pipeline outputs so Step 4 and Step 6 re-run instead of re-downloading
    _aws = shutil.which("aws") or "aws"
    _profile = ["--profile", AWS_PROFILE] if AWS_PROFILE else []
    for prefix in ("gold/cohorts_model_data/", "gold/final_model/"):
        uri = f"s3://{S3_BUCKET}/{prefix}"
        r = subprocess.run([_aws, "s3", "rm", uri, "--recursive"] + _profile, capture_output=True, text=True)
        if r.returncode == 0:
            print(f"Cleared S3 {uri}")
        else:
            print(f"S3 rm {uri}: exit {r.returncode}; {r.stderr or r.stdout or ''}")

    # 3) Local output directories
    dirs_to_clear = [
        MODEL_DATA_ROOT,
        FINAL_MODEL_OUTPUTS,
        FINAL_MODEL_OUTPUTS_ALT,
        PROJECT_ROOT / "7_shap_analysis" / "outputs",
        PROJECT_ROOT / "8_ffa_analysis" / "outputs",
    ]
    for d in dirs_to_clear:
        d = Path(d)
        if d.exists():
            shutil.rmtree(d)
            print(f"Removed {d}")
        else:
            print(f"(skip, not present) {d}")
    print("Done. Re-run Sync and then Steps 4 --> 5 --> 6 --> Step 7 --> Step 8 for a fresh run.")

## Sync required inputs from S3 to NVMe (idempotent)

Sync **cohorts** (Step 2), **feature importance** (Step 3/3b), and **Step 6** final model outputs from S3 so pipeline and data preparation can read from local/NVMe. **Idempotent:** `aws s3 sync` only updates changed or missing files.

In [ ]:
# Sync cohorts (Step 2), Step 3a/3b feature importance, and Step 6 final models from S3 to DATA_ROOT.
COHORTS_ROOT.mkdir(parents=True, exist_ok=True)
FI_SYNC_TARGET = DATA_ROOT / "gold" / "feature_importance"
FI_SYNC_TARGET.mkdir(parents=True, exist_ok=True)
FINAL_MODEL_GOLD.mkdir(parents=True, exist_ok=True)

sync_s3_to_local(f"s3://{S3_BUCKET}/gold/cohorts/", COHORTS_ROOT, profile=AWS_PROFILE)
sync_s3_to_local(f"s3://{S3_BUCKET}/gold/feature_importance/", FI_SYNC_TARGET, profile=AWS_PROFILE)
sync_s3_to_local(f"s3://{S3_BUCKET}/gold/final_model/", FINAL_MODEL_GOLD, profile=AWS_PROFILE)
print("Sync complete. Run Step 0 verification below.")

## Step 0: Verify inputs (FI required; 4_model_data and Step 6 informational)

**Required:** **Feature importance** (Step 3/3b) — must exist for each cohort/age_band so Pipeline Step 4 can run.

**Informational:** **ModelData** checks `DATA_ROOT/4_model_data` and `PROJECT_ROOT/4_model_data` (same location `create_model_data.py` writes to). **Model** = Step 6 outputs. Both are produced by Pipeline Step 4–6 cells below; if already present, you can skip those cells.

In [ ]:
def check_feature_importance(cohort: str, age_band: str) -> bool:
    """Check if feature importance exists using FileResolver pattern."""
    from py_helpers.file_resolver import FileResolver
    # Check Step 3b refined cohort feature importance first
    resolver_3b = FileResolver(
        file_type="cohort_feature_importance",
        project_root=PROJECT_ROOT,
        cohort=cohort,
        age_band=age_band,
        auto_download=False
    )
    if resolver_3b.exists():
        return True
    # Fallback to Step 3a aggregated feature importance
    resolver_3a = FileResolver(
        file_type="aggregated_feature_importance",
        project_root=PROJECT_ROOT,
        cohort=cohort,
        age_band=age_band,
        auto_download=False
    )
    return resolver_3a.exists()

def check_cohorts(cohort: str, age_band: str) -> bool:
    """Check Step 2 cohort.parquet exists for at least one year (2016-2019). Layout: COHORTS_ROOT/cohort_name=X/event_year=Y/age_band=Z/cohort.parquet."""
    for year in (2016, 2017, 2018, 2019):
        p = COHORTS_ROOT / f"cohort_name={cohort}" / f"event_year={year}" / f"age_band={age_band}" / "cohort.parquet"
        if p.exists():
            return True
    return False

def check_model_data(cohort: str, age_band: str) -> bool:
    """Check model_events.parquet at canonical MODEL_DATA_ROOT (same location create_model_data.py writes to)."""
    p = MODEL_DATA_ROOT / f"cohort_name={cohort}" / f"age_band={age_band}" / "model_events.parquet"
    return p.exists()

def check_final_model(cohort: str, age_band: str) -> bool:
    ab = age_band.replace("-", "_")
    # 1) Project or DATA_ROOT/6_final_model/outputs: cohort/65_74/models/*.joblib
    for base in (FINAL_MODEL_OUTPUTS, FINAL_MODEL_OUTPUTS_ALT):
        model_dir = base / cohort / ab
        if not model_dir.exists():
            continue
        models_sub = model_dir / "models"
        if models_sub.exists() and any(models_sub.glob("*.joblib")):
            return True
        if (model_dir / "feature_schema.json").exists():
            return True
    # 2) DATA_ROOT/gold/final_model (S3-synced): cohort/65-74/*.joblib (hyphen in age_band)
    gold_dir = FINAL_MODEL_GOLD / cohort / age_band
    if gold_dir.exists() and any(gold_dir.glob("*.joblib")):
        return True
    return False

print("Step 0: Verify feature importance (required); cohorts and 4_model_data (Step 4 inputs); Step 6 (informational)")
print("  Locations: Cohorts=COHORTS_ROOT, FI=Step 3/3b, ModelData=MODEL_DATA_ROOT, Model=Step 6 outputs")
fi_ok_all = True
for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        cohorts_ok = check_cohorts(cohort, age_band)
        fi_ok = check_feature_importance(cohort, age_band)
        model_data_ok = check_model_data(cohort, age_band)
        model_ok = check_final_model(cohort, age_band)
        if not fi_ok:
            fi_ok_all = False
        status = "ready" if fi_ok else "missing FI"
        print(f"  {cohort} / {age_band}:  Cohorts={cohorts_ok}, FI={fi_ok}, ModelData={model_data_ok}, Model={model_ok}  -> {status}")
if fi_ok_all:
    print("\nAll prerequisites are available to build model data. Run Pipeline Step 4-6 cells below.")
    print("  (If Step 6 is already built elsewhere, you can sync from S3 or skip those cells.)")
else:
    print("\nMissing feature importance for some cohort/age_band. Sync from S3 or run Step 3/3b first, then re-run this cell.")
if fi_ok_all:
    cohorts_missing = [(c, ab) for c, bands in REQUIRED_COHORTS.items() for ab in bands if not check_cohorts(c, ab)]
    if cohorts_missing:
        print("\nCohorts=False for some cohort/age_band. Sync gold/cohorts from S3 (run Sync cell) or run Step 2. Expected layout: COHORTS_ROOT/cohort_name=X/event_year=Y/age_band=Z/cohort.parquet (Y in 2016-2019).")

# Pipeline Phase 4: Model data

Build `model_events.parquet` for each cohort/age_band from Step 2 cohort data and Step 3b feature importance. Outputs go to `MODEL_DATA_ROOT/cohort_name={cohort}/age_band={age_band}/model_events.parquet`. Run the cell below for all PGx cohorts/age_bands defined in this notebook.

In [ ]:
# Pipeline Step 4: BUILD model_events.parquet by running create_model_data.py, then QA.
# The script READS: COHORTS_ROOT (cohort.parquet), gold/medical, gold/pharmacy, and feature importance.
# It WRITES: MODEL_DATA_ROOT/cohort_name={cohort}/age_band={age_band}/model_events.parquet
import duckdb

FORCE_STEP4_ED = True
FORCE_STEP4_ALL = False
REBUILT_STEP4 = set()

def _model_data_candidates(cohort: str, age_band: str):
    """Canonical location for model_events.parquet (Step 4 writes to MODEL_DATA_ROOT)."""
    return [MODEL_DATA_ROOT]

def _model_data_path(cohort: str, age_band: str) -> Path:
    """Resolve model_events.parquet path (Step 4 writes to get_model_data_root() = DATA_ROOT or PROJECT on Linux)."""
    for base in _model_data_candidates(cohort, age_band):
        p = base / f"cohort_name={cohort}" / f"age_band={age_band}" / "model_events.parquet"
        if p.exists():
            return p
    return None

def _log_model_data_qa(cohort: str, age_band: str) -> None:
    """Log location, target distribution, control:case ratio, and patient event-count balance."""
    path = _model_data_path(cohort, age_band)
    if not path:
        print(f"  [WARN] model_events.parquet not found for {cohort}/{age_band}")
        for base in _model_data_candidates(cohort, age_band):
            p = base / f"cohort_name={cohort}" / f"age_band={age_band}" / "model_events.parquet"
            print(f"    Checked: {p}  (exists: {p.exists()})")
        print(f"    Build did not write output. Check script stdout above: [INFO] data roots and example cohort path (exists=?). Layout must be {COHORTS_ROOT}/cohort_name=X/event_year=Y/age_band=Z/cohort.parquet (Y in 2016-2019). Sync cohorts to COHORTS_ROOT if needed, then re-run this cell.")
        return
    print(f"  Location: {path}")
    con = duckdb.connect()
    try:
        dist = con.execute("SELECT target, COUNT(*)::BIGINT AS n FROM read_parquet(?) GROUP BY target ORDER BY target", [str(path)]).fetchall()
        total = sum(row[1] for row in dist)
        by_target = {int(row[0]): int(row[1]) for row in dist}
        n_controls = by_target.get(0, 0)
        n_cases = by_target.get(1, 0)
        ratio = (n_controls / n_cases) if n_cases else 0
        print(f"  Target distribution: {by_target} (total rows: {total:,})")
        print(f"  Control:case ratio: {n_controls:,}:{n_cases:,} = {ratio:.2f}:1")
        event_counts = con.execute(
            """
            SELECT
              target,
              COUNT(DISTINCT mi_person_key)::BIGINT AS patients,
              AVG(n_events) AS mean_events,
              MEDIAN(n_events) AS median_events,
              MIN(n_events) AS min_events,
              MAX(n_events) AS max_events
            FROM (
              SELECT mi_person_key, target, COUNT(*) AS n_events
              FROM read_parquet(?)
              GROUP BY mi_person_key, target
            )
            GROUP BY target
            ORDER BY target
            """,
            [str(path)],
        ).df()
        print("  Patient-level event-count QA:")
        print(event_counts.to_string(index=False))
    finally:
        con.close()

for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        print(f"--> Step 4: {cohort} / {age_band} (building model_events.parquet)")
        force_step4 = FORCE_STEP4_ALL or (FORCE_STEP4_ED and cohort == "ed")
        existed_before = _model_data_path(cohort, age_band) is not None
        cmd = [sys.executable, "create_model_data.py", "--cohort", cohort, "--age_band", age_band]
        if force_step4:
            cmd.append("--force-rebuild")
        r = subprocess.run(
            cmd,
            cwd=PROJECT_ROOT / "4_model_data",
            capture_output=False,
        )
        if r.returncode != 0:
            raise SystemExit(r.returncode)
        if force_step4 or not existed_before:
            REBUILT_STEP4.add((cohort, age_band))
        _log_model_data_qa(cohort, age_band)
print("Step 4 complete.")

# Pipeline Phase 5: PGx analysis

Add PGx features (e.g. CPIC drug counts) to model data. Reads from Step 4 outputs and writes updated model data used by Step 6. Run for each cohort/age_band.

In [ ]:
# Pipeline Step 5: run_analysis.py for each REQUIRED_COHORTS (cohort, age_band)
# Set FORCE_STEP5 = True to re-run even when S3 outputs or checkpoints exist
FORCE_STEP5 = True
for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        print(f"--> Step 5: {cohort} / {age_band}")
        cmd = [sys.executable, "run_analysis.py", "--cohort-name", cohort, "--age-band", age_band]
        if FORCE_STEP5:
            cmd.append("--force")
        r = subprocess.run(cmd, cwd=PROJECT_ROOT / "5_pgx_analysis")
        if r.returncode != 0:
            raise SystemExit(r.returncode)
print("Step 5 complete.")

# Pre-training QA: model events

Run this gate after Step 4 model-data creation and Step 5 PGx enrichment, before Step 6 final model training. It validates the local `model_events.parquet` files that Step 6 will read and fails fast if any cohort/age-band is missing controls, target labels, target dates for cases, or has case events on/after the target date.

The Athena QA in `aws/athena/` gives the same style of S3-backed coverage check for persisted outputs; this cell is the local pre-training gate.

In [ ]:
# Pre-training QA gate for Step 4 model_events.parquet.
# This must pass before Step 6 final model training.
import duckdb
import pandas as pd

PRETRAIN_QA_PASSED = False
PRETRAIN_QA_ROWS = []
PRETRAIN_QA_FAILURES = []


def _pretrain_model_events_path(cohort: str, age_band: str) -> Path:
    return MODEL_DATA_ROOT / f"cohort_name={cohort}" / f"age_band={age_band}" / "model_events.parquet"


def _target_date_col(cohort: str) -> str:
    return "first_fall_date" if cohort == "falls" else "first_ed_date"


def _qa_one_model_events(cohort: str, age_band: str) -> None:
    path = _pretrain_model_events_path(cohort, age_band)
    if not path.exists():
        PRETRAIN_QA_FAILURES.append(f"{cohort}/{age_band}: missing model_events.parquet at {path}")
        PRETRAIN_QA_ROWS.append({"cohort": cohort, "age_band": age_band, "status": "missing", "path": str(path)})
        return

    target_date_col = _target_date_col(cohort)
    path_sql = str(path).replace("'", "''")
    con = duckdb.connect()
    try:
        cols = [row[0] for row in con.execute(f"DESCRIBE SELECT * FROM read_parquet('{path_sql}')").fetchall()]
        required_cols = {"mi_person_key", "event_date", "target", target_date_col}
        missing_cols = sorted(required_cols - set(cols))
        if missing_cols:
            PRETRAIN_QA_FAILURES.append(f"{cohort}/{age_band}: missing required columns {missing_cols} in {path}")
            PRETRAIN_QA_ROWS.append({"cohort": cohort, "age_band": age_band, "status": "missing_columns", "path": str(path)})
            return

        qa = con.execute(
            f"""
            SELECT
                COUNT(*)::BIGINT AS rows,
                COUNT(DISTINCT mi_person_key)::BIGINT AS patients,
                COUNT(*) FILTER (WHERE target = 1)::BIGINT AS case_rows,
                COUNT(*) FILTER (WHERE target = 0)::BIGINT AS control_rows,
                COUNT(DISTINCT CASE WHEN target = 1 THEN mi_person_key END)::BIGINT AS case_patients,
                COUNT(DISTINCT CASE WHEN target = 0 THEN mi_person_key END)::BIGINT AS control_patients,
                SUM(CASE WHEN mi_person_key IS NULL THEN 1 ELSE 0 END)::BIGINT AS null_patient_rows,
                SUM(CASE WHEN event_date IS NULL THEN 1 ELSE 0 END)::BIGINT AS null_event_date_rows,
                SUM(CASE WHEN target NOT IN (0, 1) OR target IS NULL THEN 1 ELSE 0 END)::BIGINT AS invalid_target_rows,
                SUM(CASE WHEN target = 1 AND "{target_date_col}" IS NULL THEN 1 ELSE 0 END)::BIGINT AS case_rows_missing_target_date,
                SUM(
                    CASE
                        WHEN target = 1
                         AND "{target_date_col}" IS NOT NULL
                         AND event_date IS NOT NULL
                         AND CAST(event_date AS DATE) >= CAST("{target_date_col}" AS DATE)
                        THEN 1 ELSE 0
                    END
                )::BIGINT AS case_rows_on_or_after_target,
                MIN(event_date) AS min_event_date,
                MAX(event_date) AS max_event_date
            FROM read_parquet('{path_sql}')
            """
        ).df().iloc[0].to_dict()

        row = {
            "cohort": cohort,
            "age_band": age_band,
            "status": "ok",
            "path": str(path),
            **qa,
        }
        row["control_to_case_patient_ratio"] = (
            float(row["control_patients"]) / float(row["case_patients"])
            if int(row["case_patients"] or 0) else None
        )

        if "drug_name" in cols:
            drug_qa = con.execute(
                f"""
                SELECT
                    COUNT(*) FILTER (WHERE drug_name IS NOT NULL)::BIGINT AS drug_rows,
                    COUNT(*) FILTER (WHERE target = 1 AND drug_name IS NOT NULL)::BIGINT AS case_drug_rows,
                    COUNT(*) FILTER (WHERE target = 0 AND drug_name IS NOT NULL)::BIGINT AS control_drug_rows
                FROM read_parquet('{path_sql}')
                """
            ).df().iloc[0].to_dict()
            row.update(drug_qa)
        else:
            row.update({"drug_rows": None, "case_drug_rows": None, "control_drug_rows": None})

        PRETRAIN_QA_ROWS.append(row)

        hard_fail_checks = {
            "no_rows": int(row["rows"] or 0) == 0,
            "no_case_rows": int(row["case_rows"] or 0) == 0,
            "no_control_rows": int(row["control_rows"] or 0) == 0,
            "no_case_patients": int(row["case_patients"] or 0) == 0,
            "no_control_patients": int(row["control_patients"] or 0) == 0,
            "null_patient_rows": int(row["null_patient_rows"] or 0) > 0,
            "null_event_date_rows": int(row["null_event_date_rows"] or 0) > 0,
            "invalid_target_rows": int(row["invalid_target_rows"] or 0) > 0,
            "case_rows_missing_target_date": int(row["case_rows_missing_target_date"] or 0) > 0,
            "case_rows_on_or_after_target": int(row["case_rows_on_or_after_target"] or 0) > 0,
        }
        if cohort == "ed":
            hard_fail_checks["ed_no_case_drug_rows"] = int(row.get("case_drug_rows") or 0) == 0
            hard_fail_checks["ed_no_control_drug_rows"] = int(row.get("control_drug_rows") or 0) == 0

        failed = [name for name, failed_check in hard_fail_checks.items() if failed_check]
        if failed:
            PRETRAIN_QA_FAILURES.append(f"{cohort}/{age_band}: failed {failed}; path={path}")
    finally:
        con.close()


for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        print(f"--> Pre-training QA: {cohort} / {age_band}")
        _qa_one_model_events(cohort, age_band)

qa_df = pd.DataFrame(PRETRAIN_QA_ROWS)
if not qa_df.empty:
    display_cols = [
        "cohort",
        "age_band",
        "status",
        "rows",
        "patients",
        "case_rows",
        "control_rows",
        "case_patients",
        "control_patients",
        "control_to_case_patient_ratio",
        "null_event_date_rows",
        "case_rows_missing_target_date",
        "case_rows_on_or_after_target",
        "drug_rows",
        "case_drug_rows",
        "control_drug_rows",
    ]
    display(qa_df[[c for c in display_cols if c in qa_df.columns]])

if PRETRAIN_QA_FAILURES:
    print("[X] Pre-training QA failed:")
    for failure in PRETRAIN_QA_FAILURES:
        print(f"  - {failure}")
    print("\n[ACTION] Pull the latest repo updates on EC2, rerun the Step 4 model-data cell, then rerun this QA cell.")
    print("         Step 4 now rebuilds cached model_events files with null event_date rows.")
    raise RuntimeError("Pre-training model-events QA failed; fix Step 4 model_events before running Step 6.")

PRETRAIN_QA_PASSED = True
print("[1] Pre-training model-events QA passed for all configured cohorts and age bands.")

# Pipeline Phase 6: Model Outputs, SHAP, FFA, and Performance Review

Train final models per cohort/age band, then run the interpretability and review steps in this order:

- **SHAP Values**
- **FFA Analysis**
- **Combined SHAP+FFA**
  - **Top 20 Consensus Feature Importance**
- **Model Performance per density bin**
  - **Model Performance Summary**

Step 6 model training uses **per-bin** training by default (`--train-mode per_bin`) for both `falls` and `ed`: separate models under `outputs/.../bin_models/{low|medium|high|extreme}/`, then mirrors one bin (prefer `medium`) to the cohort-level `outputs/.../{age_band}/` tree for prepare_models / Lambda. Use `--train-mode aggregate` for a single cohort-wide model only, or `both` for cohort-wide plus per-bin.

In [7]:
# Pipeline Step 6: run_final_model.py for each REQUIRED_COHORTS (cohort, age_band)
# Note: script uses --age_band (underscore). Default --train-mode is per_bin (omit flag).
if globals().get("PRETRAIN_QA_PASSED") is not True:
    raise RuntimeError("Run and pass the Pre-training QA: model events cell before Step 6 training.")

FORCE_STEP6 = False
FORCE_STEP6_REBUILT_ONLY = True
STEP6_TRAIN_MODE = None
rebuilt_step4 = globals().get("REBUILT_STEP4", set())
for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        print(f"--> Step 6: {cohort} / {age_band}")
        cmd = [sys.executable, "run_final_model.py", "--cohort", cohort, "--age_band", age_band]
        if STEP6_TRAIN_MODE:
            cmd.extend(["--train-mode", STEP6_TRAIN_MODE])
        force_step6 = FORCE_STEP6 or (FORCE_STEP6_REBUILT_ONLY and (cohort, age_band) in rebuilt_step4)
        if force_step6:
            cmd.append("--force-retrain")
        r = subprocess.run(
            cmd,
            cwd=PROJECT_ROOT / "6_final_model",
        )
        if r.returncode != 0:
            cmd_text = " ".join(str(part) for part in cmd)
            raise RuntimeError(
                f"Step 6 failed for {cohort}/{age_band} with return code {r.returncode}. "
                f"Command: {cmd_text}"
            )
print("Step 6 complete.")

--> Step 6: falls / 65-74
--> Step 6: falls / 75-84
--> Step 6: ed / 65-74
--> Step 6: ed / 75-84
Step 6 complete.

## SHAP Values

**7_shap_analysis/run_shap_analysis.py** runs per-bin SHAP for bins trained in Step 6 and falls back to cohort-level SHAP if only aggregate models exist.

In [8]:
import logging
logger = logging.getLogger(__name__)

from py_helpers.event_density_utils import (
    cohort_aggregate_final_model_has_artifacts,
    list_trained_density_bins,
)

SHAP_SCRIPT = PROJECT_ROOT / "7_shap_analysis" / "run_shap_analysis.py"
for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        trained = list_trained_density_bins(PROJECT_ROOT, cohort, age_band)
        if trained:
            for bin_name in trained:
                print(f"--> Step 7 (SHAP bin={bin_name}): {cohort} / {age_band}")
                r = subprocess.run(
                    [sys.executable, str(SHAP_SCRIPT),
                     "--cohort", cohort, "--age_band", age_band, "--bin", bin_name],
                    cwd=PROJECT_ROOT,
                )
                if r.returncode != 0:
                    raise SystemExit(r.returncode)
        elif cohort_aggregate_final_model_has_artifacts(PROJECT_ROOT, cohort, age_band):
            print(f"--> Step 7 (SHAP cohort-level): {cohort} / {age_band}")
            r = subprocess.run(
                [sys.executable, str(SHAP_SCRIPT), "--cohort", cohort, "--age_band", age_band],
                cwd=PROJECT_ROOT,
            )
            if r.returncode != 0:
                raise SystemExit(r.returncode)
        else:
            print(f"[skip] Step 7: no Step 6 models for {cohort} / {age_band}")
print("Step 7 (SHAP) complete.")

--> Step 7 (SHAP bin=low): falls / 65-74

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/low
  Summary - found: ['low']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/65-74
--> Step 7 (SHAP bin=medium): falls / 65-74

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/65-74
--> Step 7 (SHAP bin=high): falls / 65-74

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/high
  Summary - found: ['high']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/65-74
--> Step 7 (SHAP bin=extreme): falls / 65-74

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/65-74
--> Step 7 (SHAP bin=low): falls / 75-84

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/low
  Summary - found: ['low']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/75-84
--> Step 7 (SHAP bin=medium): falls / 75-84

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/75-84
--> Step 7 (SHAP bin=high): falls / 75-84

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/high
  Summary - found: ['high']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/75-84
--> Step 7 (SHAP bin=extreme): falls / 75-84

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for falls/75-84
--> Step 7 (SHAP bin=low): ed / 65-74

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/low
  Summary - found: ['low']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/65-74
--> Step 7 (SHAP bin=medium): ed / 65-74

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/65-74
--> Step 7 (SHAP bin=high): ed / 65-74

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/high
  Summary - found: ['high']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/65-74
--> Step 7 (SHAP bin=extreme): ed / 65-74

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/65-74
--> Step 7 (SHAP bin=low): ed / 75-84

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/low
  Summary - found: ['low']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/75-84
--> Step 7 (SHAP bin=medium): ed / 75-84

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/75-84
--> Step 7 (SHAP bin=high): ed / 75-84

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/high
  Summary - found: ['high']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/75-84
--> Step 7 (SHAP bin=extreme): ed / 75-84

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

[SKIP] Step 7 outputs already exist locally for ed/75-84
Step 7 (SHAP) complete.

### Review: SHAP Output Files

Confirm SHAP value parquets exist for each cohort/age band or per-bin model immediately after SHAP completes.

In [9]:
SHAP_OUTPUTS = PROJECT_ROOT / "7_shap_analysis" / "outputs"
print("SHAP outputs:")
if SHAP_OUTPUTS.exists():
    files = sorted(SHAP_OUTPUTS.rglob("*.parquet"))
    for f in files:
        size_mb = f.stat().st_size / 1e6
        print(f"  {f.relative_to(PROJECT_ROOT)}  ({size_mb:.1f} MB)")
    if not files:
        print("  (no parquet files yet - run Step 7)")
else:
    print(f"  {SHAP_OUTPUTS} does not exist - run Step 7")

SHAP outputs:
  7_shap_analysis/outputs/ed/65_74/bin_models/extreme/ed_65_74_shap_sample_values_catboost.parquet  (0.1 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/extreme/ed_65_74_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/high/ed_65_74_shap_sample_values_catboost.parquet  (0.4 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/high/ed_65_74_shap_sample_values_xgboost.parquet  (0.2 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/low/ed_65_74_shap_sample_values_catboost.parquet  (0.3 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/low/ed_65_74_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/medium/ed_65_74_shap_sample_values_catboost.parquet  (0.2 MB)
  7_shap_analysis/outputs/ed/65_74/bin_models/medium/ed_65_74_shap_sample_values_xgboost.parquet  (0.1 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/extreme/ed_75_84_shap_sample_values_catboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/extreme/ed_75_84_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/high/ed_75_84_shap_sample_values_catboost.parquet  (0.1 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/high/ed_75_84_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/low/ed_75_84_shap_sample_values_catboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/low/ed_75_84_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/medium/ed_75_84_shap_sample_values_catboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/ed/75_84/bin_models/medium/ed_75_84_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/extreme/falls_65_74_shap_sample_values_catboost.parquet  (0.2 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/extreme/falls_65_74_shap_sample_values_xgboost.parquet  (0.1 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/high/falls_65_74_shap_sample_values_catboost.parquet  (1.3 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/high/falls_65_74_shap_sample_values_xgboost.parquet  (0.2 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/low/falls_65_74_shap_sample_values_catboost.parquet  (0.8 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/low/falls_65_74_shap_sample_values_xgboost.parquet  (0.2 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/medium/falls_65_74_shap_sample_values_catboost.parquet  (0.7 MB)
  7_shap_analysis/outputs/falls/65_74/bin_models/medium/falls_65_74_shap_sample_values_xgboost.parquet  (0.3 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/extreme/falls_75_84_shap_sample_values_catboost.parquet  (0.2 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/extreme/falls_75_84_shap_sample_values_xgboost.parquet  (0.0 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/high/falls_75_84_shap_sample_values_catboost.parquet  (0.5 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/high/falls_75_84_shap_sample_values_xgboost.parquet  (0.1 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/low/falls_75_84_shap_sample_values_catboost.parquet  (0.6 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/low/falls_75_84_shap_sample_values_xgboost.parquet  (0.4 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/medium/falls_75_84_shap_sample_values_catboost.parquet  (0.8 MB)
  7_shap_analysis/outputs/falls/75_84/bin_models/medium/falls_75_84_shap_sample_values_xgboost.parquet  (0.2 MB)

## FFA Analysis

**8_ffa_analysis/run_ffa_workflow.py** runs after SHAP. Per-bin resolution mirrors the SHAP step, writes FFA outputs under `8_ffa_analysis/outputs/`, and then invokes the combined SHAP+FFA artifact builder.

In [10]:
from py_helpers.event_density_utils import (
    cohort_aggregate_final_model_has_artifacts,
    list_trained_density_bins,
)

FFA_SCRIPT = PROJECT_ROOT / "8_ffa_analysis" / "run_ffa_workflow.py"
for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        trained = list_trained_density_bins(PROJECT_ROOT, cohort, age_band)
        if trained:
            for bin_name in trained:
                print(f"--> Step 8 (FFA + combine bin={bin_name}): {cohort} / {age_band}")
                cmd = [
                    sys.executable, str(FFA_SCRIPT),
                    "--cohort", cohort, "--age-band", age_band, "--bin", bin_name,
                ]
                r = subprocess.run(cmd, cwd=PROJECT_ROOT)
                if r.returncode != 0:
                    cmd_text = " ".join(str(part) for part in cmd)
                    raise RuntimeError(
                        f"Step 8 FFA+combine failed for {cohort}/{age_band} bin={bin_name} "
                        f"with return code {r.returncode}. Command: {cmd_text}"
                    )
        elif cohort_aggregate_final_model_has_artifacts(PROJECT_ROOT, cohort, age_band):
            print(f"--> Step 8 (FFA + combine cohort-level): {cohort} / {age_band}")
            cmd = [sys.executable, str(FFA_SCRIPT), "--cohort", cohort, "--age-band", age_band]
            r = subprocess.run(cmd, cwd=PROJECT_ROOT)
            if r.returncode != 0:
                cmd_text = " ".join(str(part) for part in cmd)
                raise RuntimeError(
                    f"Step 8 FFA+combine failed for {cohort}/{age_band} "
                    f"with return code {r.returncode}. Command: {cmd_text}"
                )
        else:
            print(f"[skip] Step 8: no Step 6 models for {cohort} / {age_band}")
print("Step 8 (FFA + combined SHAP/FFA artifacts) complete.")

--> Step 8 (FFA + combine bin=low): falls / 65-74

2026-06-21 02:27:23,636 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:24,430 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:24,508 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/low/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:24,522 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/low/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:24,535 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/low/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:24,568 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 65-74 --workers 1 --bin low --upload-to-gold
2026-06-21 02:27:24,875 - INFO - Combining SHAP + FFA for falls/65-74 bin=low
2026-06-21 02:27:25,988 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:26,088 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/dashboard_data.json (skipping upload)
2026-06-21 02:27:26,101 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/combined_importance.csv (skipping upload)
2026-06-21 02:27:26,116 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:26,130 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:26,147 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/consensus_features.json (skipping upload)
2026-06-21 02:27:26,161 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/patient_explanations.csv (skipping upload)
2026-06-21 02:27:26,183 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/low/summary_report.txt (skipping upload)
2026-06-21 02:27:26,224 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/65_74/bin_models/low
2026-06-21 02:27:26,424 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 11, icd: 23, cpt: 67, other: 1

CONSENSUS FEATURES:
  - Consensus features: 17
  - SHAP-only features: 3
  - FFA-only features: 3
  - Consensus rate: 85.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_cpt_99213: 0.4944 (SHAP: 0.702, FFA: 0.287)
  3. item_cpt_99214: 0.4047 (SHAP: 0.584, FFA: 0.226)
  4. item_drug_OMEPRAZOLE: 0.1511 (SHAP: 0.260, FFA: 0.042)
  5. item_drug_SIMVASTATIN: 0.1396 (SHAP: 0.241, FFA: 0.039)
  6. item_cpt_99212: 0.1065 (SHAP: 0.190, FFA: 0.023)
  7. item_cpt_85025: 0.1054 (SHAP: 0.183, FFA: 0.027)
  8. item_cpt_84443: 0.1033 (SHAP: 0.186, FFA: 0.020)
  9. item_drug_LISINOPRIL: 0.1009 (SHAP: 0.176, FFA: 0.025)
  10. item_cpt_90662: 0.0893 (SHAP: 0.154, FFA: 0.024)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 377
  - Patients with consensus features: 377

================================================================================

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/low
  Summary - found: ['low']  |  missing: (none)

--> Step 8 (FFA + combine bin=medium): falls / 65-74

2026-06-21 02:27:26,926 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:27,720 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:27,800 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/medium/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:27,810 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/medium/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:27,825 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/medium/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:27,867 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 65-74 --workers 1 --bin medium --upload-to-gold
2026-06-21 02:27:28,175 - INFO - Combining SHAP + FFA for falls/65-74 bin=medium
2026-06-21 02:27:29,245 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:29,338 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/dashboard_data.json (skipping upload)
2026-06-21 02:27:29,355 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/combined_importance.csv (skipping upload)
2026-06-21 02:27:29,367 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:29,383 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:29,400 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/consensus_features.json (skipping upload)
2026-06-21 02:27:29,413 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/patient_explanations.csv (skipping upload)
2026-06-21 02:27:29,426 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/medium/summary_report.txt (skipping upload)
2026-06-21 02:27:29,531 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/65_74/bin_models/medium
2026-06-21 02:27:29,729 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 17, icd: 35, cpt: 100, other: 1

CONSENSUS FEATURES:
  - Consensus features: 19
  - SHAP-only features: 1
  - FFA-only features: 1
  - Consensus rate: 95.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_cpt_99215: 0.3955 (SHAP: 0.586, FFA: 0.205)
  3. item_cpt_99214: 0.2646 (SHAP: 0.423, FFA: 0.106)
  4. item_cpt_97110: 0.2038 (SHAP: 0.345, FFA: 0.063)
  5. item_icd_Z23: 0.1938 (SHAP: 0.323, FFA: 0.065)
  6. item_cpt_93005: 0.1492 (SHAP: 0.258, FFA: 0.040)
  7. item_cpt_88305: 0.1473 (SHAP: 0.262, FFA: 0.033)
  8. item_cpt_93000: 0.1186 (SHAP: 0.203, FFA: 0.034)
  9. item_cpt_36415: 0.1077 (SHAP: 0.193, FFA: 0.022)
  10. item_cpt_99213: 0.1023 (SHAP: 0.182, FFA: 0.023)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 266
  - Patients with consensus features: 266

================================================================================

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

--> Step 8 (FFA + combine bin=high): falls / 65-74

2026-06-21 02:27:30,227 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:31,014 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:31,119 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/high/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:31,135 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/high/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:31,151 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/high/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:31,188 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 65-74 --workers 1 --bin high --upload-to-gold
2026-06-21 02:27:31,493 - INFO - Combining SHAP + FFA for falls/65-74 bin=high
2026-06-21 02:27:32,573 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:32,657 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/dashboard_data.json (skipping upload)
2026-06-21 02:27:32,669 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/combined_importance.csv (skipping upload)
2026-06-21 02:27:32,680 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:32,690 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:32,704 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/consensus_features.json (skipping upload)
2026-06-21 02:27:32,715 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/patient_explanations.csv (skipping upload)
2026-06-21 02:27:32,727 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/high/summary_report.txt (skipping upload)
2026-06-21 02:27:32,765 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/65_74/bin_models/high

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 17, icd: 27, cpt: 105, other: 1

CONSENSUS FEATURES:
  - Consensus features: 20
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 100.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_icd_R0602: 0.1862 (SHAP: 0.310, FFA: 0.063)
  3. item_drug_FUROSEMIDE: 0.1769 (SHAP: 0.292, FFA: 0.062)
  4. item_cpt_80061: 0.1623 (SHAP: 0.275, FFA: 0.049)
  5. item_icd_I10: 0.1421 (SHAP: 0.246, FFA: 0.038)
  6. item_cpt_80048: 0.1141 (SHAP: 0.197, FFA: 0.031)
  7. item_cpt_83735: 0.1107 (SHAP: 0.194, FFA: 0.027)
  8. item_icd_Z23: 0.1066 (SHAP: 0.188, FFA: 0.025)
  9. item_cpt_71020: 0.1000 (SHAP: 0.175, FFA: 0.025)
  10. item_drug_GABAPENTIN: 0.0959 (SHAP: 0.171, FFA: 0.021)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 286
  - Patients with consensus features: 286

================================================================================

2026-06-21 02:27:32,969 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/high
  Summary - found: ['high']  |  missing: (none)

--> Step 8 (FFA + combine bin=extreme): falls / 65-74

2026-06-21 02:27:33,461 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:34,246 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:34,327 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/extreme/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:34,340 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/extreme/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:34,351 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/65-74/bin_models/extreme/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:34,381 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 65-74 --workers 1 --bin extreme --upload-to-gold
2026-06-21 02:27:34,685 - INFO - Combining SHAP + FFA for falls/65-74 bin=extreme
2026-06-21 02:27:35,563 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:35,645 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/dashboard_data.json (skipping upload)
2026-06-21 02:27:35,659 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/combined_importance.csv (skipping upload)
2026-06-21 02:27:35,674 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:35,685 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:35,697 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/consensus_features.json (skipping upload)
2026-06-21 02:27:35,709 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/patient_explanations.csv (skipping upload)
2026-06-21 02:27:35,719 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/65-74/bin_models/extreme/summary_report.txt (skipping upload)
2026-06-21 02:27:35,759 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/65_74/bin_models/extreme

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 17, icd: 35, cpt: 100, other: 1

CONSENSUS FEATURES:
  - Consensus features: 15
  - SHAP-only features: 5
  - FFA-only features: 5
  - Consensus rate: 75.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_cpt_99215: 0.3773 (SHAP: 0.559, FFA: 0.196)
  3. item_cpt_70450: 0.1195 (SHAP: 0.218, FFA: 0.021)
  4. item_cpt_93005: 0.1122 (SHAP: 0.194, FFA: 0.030)
  5. item_cpt_97110: 0.0869 (SHAP: 0.147, FFA: 0.027)
  6. item_cpt_85610: 0.0770 (SHAP: 0.139, FFA: 0.015)
  7. item_cpt_99214: 0.0752 (SHAP: 0.120, FFA: 0.030)
  8. item_icd_Z23: 0.0732 (SHAP: 0.122, FFA: 0.024)
  9. item_cpt_99233: 0.0646 (SHAP: 0.122, FFA: 0.007)
  10. item_cpt_88305: 0.0555 (SHAP: 0.099, FFA: 0.012)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 27
  - Patients with consensus features: 27

================================================================================

=== Per-bin Step 6 output validation: falls / 65-74 ===
  Canonical path: 6_final_model/outputs/falls/65_74/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/65_74/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

2026-06-21 02:27:35,952 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

--> Step 8 (FFA + combine bin=low): falls / 75-84

2026-06-21 02:27:36,438 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:37,221 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:37,314 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/low/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:37,325 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/low/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:37,337 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/low/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:37,371 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 75-84 --workers 1 --bin low --upload-to-gold
2026-06-21 02:27:37,675 - INFO - Combining SHAP + FFA for falls/75-84 bin=low
2026-06-21 02:27:38,895 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:38,984 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/dashboard_data.json (skipping upload)
2026-06-21 02:27:38,997 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/combined_importance.csv (skipping upload)
2026-06-21 02:27:39,009 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:39,022 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:39,033 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/consensus_features.json (skipping upload)
2026-06-21 02:27:39,046 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/patient_explanations.csv (skipping upload)
2026-06-21 02:27:39,057 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/low/summary_report.txt (skipping upload)
2026-06-21 02:27:39,094 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/75_84/bin_models/low

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 12, icd: 47, cpt: 88, other: 1

CONSENSUS FEATURES:
  - Consensus features: 17
  - SHAP-only features: 3
  - FFA-only features: 3
  - Consensus rate: 85.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_cpt_99214: 0.4248 (SHAP: 0.640, FFA: 0.210)
  3. item_cpt_99213: 0.1558 (SHAP: 0.249, FFA: 0.063)
  4. item_cpt_85610: 0.0742 (SHAP: 0.135, FFA: 0.013)
  5. item_cpt_99215: 0.0728 (SHAP: 0.132, FFA: 0.013)
  6. item_cpt_90662: 0.0654 (SHAP: 0.120, FFA: 0.011)
  7. item_cpt_70450: 0.0628 (SHAP: 0.116, FFA: 0.010)
  8. item_cpt_82306: 0.0561 (SHAP: 0.102, FFA: 0.011)
  9. item_cpt_80061: 0.0548 (SHAP: 0.096, FFA: 0.013)
  10. item_drug_LISINOPRIL: 0.0529 (SHAP: 0.099, FFA: 0.007)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 474
  - Patients with consensus features: 474

================================================================================

2026-06-21 02:27:39,298 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/low
  Summary - found: ['low']  |  missing: (none)

--> Step 8 (FFA + combine bin=medium): falls / 75-84

2026-06-21 02:27:39,798 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:40,598 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:40,720 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/medium/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:40,733 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/medium/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:40,750 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/medium/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:40,789 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 75-84 --workers 1 --bin medium --upload-to-gold
2026-06-21 02:27:41,102 - INFO - Combining SHAP + FFA for falls/75-84 bin=medium
2026-06-21 02:27:42,139 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:42,226 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/dashboard_data.json (skipping upload)
2026-06-21 02:27:42,240 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/combined_importance.csv (skipping upload)
2026-06-21 02:27:42,253 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:42,268 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:42,283 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/consensus_features.json (skipping upload)
2026-06-21 02:27:42,298 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/patient_explanations.csv (skipping upload)
2026-06-21 02:27:42,312 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/medium/summary_report.txt (skipping upload)
2026-06-21 02:27:42,385 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/75_84/bin_models/medium

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 6, icd: 16, cpt: 75, other: 1

CONSENSUS FEATURES:
  - Consensus features: 19
  - SHAP-only features: 1
  - FFA-only features: 1
  - Consensus rate: 95.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_cpt_93010: 0.2274 (SHAP: 0.385, FFA: 0.070)
  3. item_cpt_97110: 0.1651 (SHAP: 0.286, FFA: 0.045)
  4. item_drug_GABAPENTIN: 0.1632 (SHAP: 0.271, FFA: 0.055)
  5. item_cpt_36415: 0.1514 (SHAP: 0.251, FFA: 0.052)
  6. item_drug_PREDNISONE: 0.1388 (SHAP: 0.224, FFA: 0.054)
  7. item_cpt_20610: 0.1202 (SHAP: 0.203, FFA: 0.037)
  8. item_cpt_90662: 0.1115 (SHAP: 0.201, FFA: 0.022)
  9. item_icd_I10: 0.0918 (SHAP: 0.166, FFA: 0.018)
  10. item_cpt_80048: 0.0796 (SHAP: 0.146, FFA: 0.014)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 351
  - Patients with consensus features: 351

================================================================================

2026-06-21 02:27:42,620 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

--> Step 8 (FFA + combine bin=high): falls / 75-84

2026-06-21 02:27:43,167 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:43,988 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:44,070 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/high/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:44,082 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/high/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:44,094 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/high/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:44,125 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 75-84 --workers 1 --bin high --upload-to-gold
2026-06-21 02:27:44,437 - INFO - Combining SHAP + FFA for falls/75-84 bin=high
2026-06-21 02:27:45,567 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:45,629 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/dashboard_data.json (skipping upload)
2026-06-21 02:27:45,639 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/combined_importance.csv (skipping upload)
2026-06-21 02:27:45,650 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:45,715 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:45,729 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/consensus_features.json (skipping upload)
2026-06-21 02:27:45,742 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/patient_explanations.csv (skipping upload)
2026-06-21 02:27:45,756 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/high/summary_report.txt (skipping upload)
2026-06-21 02:27:45,783 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/75_84/bin_models/high

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 2, icd: 20, cpt: 66, other: 1

CONSENSUS FEATURES:
  - Consensus features: 19
  - SHAP-only features: 1
  - FFA-only features: 1
  - Consensus rate: 95.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_cpt_71010: 0.3213 (SHAP: 0.478, FFA: 0.165)
  3. item_icd_Z23: 0.2940 (SHAP: 0.450, FFA: 0.138)
  4. item_icd_I4891: 0.2619 (SHAP: 0.409, FFA: 0.115)
  5. item_icd_R0602: 0.2292 (SHAP: 0.364, FFA: 0.095)
  6. item_cpt_97162: 0.2239 (SHAP: 0.346, FFA: 0.101)
  7. item_drug_GABAPENTIN: 0.2039 (SHAP: 0.322, FFA: 0.086)
  8. item_cpt_99308: 0.1833 (SHAP: 0.296, FFA: 0.071)
  9. item_cpt_99204: 0.1817 (SHAP: 0.292, FFA: 0.072)
  10. item_cpt_83036: 0.1787 (SHAP: 0.292, FFA: 0.065)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 352
  - Patients with consensus features: 352

================================================================================

2026-06-21 02:27:46,025 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/high
  Summary - found: ['high']  |  missing: (none)

--> Step 8 (FFA + combine bin=extreme): falls / 75-84

2026-06-21 02:27:46,565 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:47,380 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:47,484 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/extreme/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:47,501 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/extreme/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:47,524 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/falls/75-84/bin_models/extreme/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:47,563 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort falls --age-band 75-84 --workers 1 --bin extreme --upload-to-gold
2026-06-21 02:27:47,877 - INFO - Combining SHAP + FFA for falls/75-84 bin=extreme
2026-06-21 02:27:48,788 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:48,872 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/dashboard_data.json (skipping upload)
2026-06-21 02:27:48,890 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/combined_importance.csv (skipping upload)
2026-06-21 02:27:48,904 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:48,916 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:48,930 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/consensus_features.json (skipping upload)
2026-06-21 02:27:48,943 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/patient_explanations.csv (skipping upload)
2026-06-21 02:27:48,959 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/falls/75-84/bin_models/extreme/summary_report.txt (skipping upload)
2026-06-21 02:27:48,990 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/falls/75_84/bin_models/extreme

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: falls / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 6, icd: 16, cpt: 75, other: 1

CONSENSUS FEATURES:
  - Consensus features: 17
  - SHAP-only features: 3
  - FFA-only features: 3
  - Consensus rate: 85.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_PREDNISONE: 0.1084 (SHAP: 0.175, FFA: 0.042)
  3. item_cpt_93010: 0.0966 (SHAP: 0.164, FFA: 0.030)
  4. item_cpt_20610: 0.0883 (SHAP: 0.149, FFA: 0.027)
  5. item_cpt_97110: 0.0730 (SHAP: 0.126, FFA: 0.020)
  6. item_drug_GABAPENTIN: 0.0677 (SHAP: 0.113, FFA: 0.023)
  7. item_cpt_96374: 0.0672 (SHAP: 0.122, FFA: 0.012)
  8. item_drug_FUROSEMIDE: 0.0589 (SHAP: 0.108, FFA: 0.009)
  9. item_cpt_36415: 0.0458 (SHAP: 0.076, FFA: 0.016)
  10. item_cpt_97001: 0.0443 (SHAP: 0.083, FFA: 0.006)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 23
  - Patients with consensus features: 23

================================================================================

2026-06-21 02:27:49,244 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: falls / 75-84 ===
  Canonical path: 6_final_model/outputs/falls/75_84/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/falls/75_84/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

--> Step 8 (FFA + combine bin=low): ed / 65-74

2026-06-21 02:27:49,787 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:50,611 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:50,699 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/low/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:50,712 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/low/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:50,722 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/low/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:50,752 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 65-74 --workers 1 --bin low --upload-to-gold
2026-06-21 02:27:51,071 - INFO - Combining SHAP + FFA for ed/65-74 bin=low
2026-06-21 02:27:52,743 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:52,839 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/dashboard_data.json (skipping upload)
2026-06-21 02:27:52,852 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/combined_importance.csv (skipping upload)
2026-06-21 02:27:52,870 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:52,886 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:52,900 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/consensus_features.json (skipping upload)
2026-06-21 02:27:52,915 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/patient_explanations.csv (skipping upload)
2026-06-21 02:27:52,925 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/low/summary_report.txt (skipping upload)
2026-06-21 02:27:53,019 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/65_74/bin_models/low

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 7, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 8
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 40.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_SIMVASTATIN: 0.0216 (SHAP: 0.038, FFA: 0.006)
  3. item_drug_AMOXICILLIN: 0.0172 (SHAP: 0.031, FFA: 0.004)
  4. item_drug_LISINOPRIL: 0.0107 (SHAP: 0.019, FFA: 0.002)
  5. item_drug_PREDNISONE: 0.0102 (SHAP: 0.019, FFA: 0.002)
  6. item_drug_HYDROCHLOROTHIAZIDE: 0.0096 (SHAP: 0.017, FFA: 0.002)
  7. item_drug_AZITHROMYCIN: 0.0089 (SHAP: 0.016, FFA: 0.002)
  8. item_drug_OMEPRAZOLE: 0.0000 (SHAP: 0.000, FFA: 0.000)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 1890
  - Patients with consensus features: 1890

================================================================================

2026-06-21 02:27:53,261 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/low
  Summary - found: ['low']  |  missing: (none)

--> Step 8 (FFA + combine bin=medium): ed / 65-74

2026-06-21 02:27:53,806 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:54,636 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:54,721 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/medium/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:54,736 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/medium/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:54,749 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/medium/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:54,782 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 65-74 --workers 1 --bin medium --upload-to-gold
2026-06-21 02:27:55,098 - INFO - Combining SHAP + FFA for ed/65-74 bin=medium
2026-06-21 02:27:56,299 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:56,390 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/dashboard_data.json (skipping upload)
2026-06-21 02:27:56,405 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/combined_importance.csv (skipping upload)
2026-06-21 02:27:56,417 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/combined_shap_importance.csv (skipping upload)
2026-06-21 02:27:56,429 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/top_interaction_factors.csv (skipping upload)
2026-06-21 02:27:56,442 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/consensus_features.json (skipping upload)
2026-06-21 02:27:56,455 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/patient_explanations.csv (skipping upload)
2026-06-21 02:27:56,467 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/medium/summary_report.txt (skipping upload)
2026-06-21 02:27:56,507 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/65_74/bin_models/medium

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 30, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 20
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 100.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_SIMVASTATIN: 0.0374 (SHAP: 0.066, FFA: 0.009)
  3. item_drug_FUROSEMIDE: 0.0347 (SHAP: 0.061, FFA: 0.008)
  4. item_drug_AMOXICILLIN: 0.0219 (SHAP: 0.040, FFA: 0.004)
  5. item_drug_ALPRAZOLAM: 0.0088 (SHAP: 0.017, FFA: 0.001)
  6. item_drug_LISINOPRIL: 0.0057 (SHAP: 0.011, FFA: 0.000)
  7. item_drug_CARVEDILOL: 0.0042 (SHAP: 0.008, FFA: 0.000)
  8. item_drug_MELOXICAM: 0.0041 (SHAP: 0.008, FFA: 0.000)
  9. item_drug_HYDROCHLOROTHIAZIDE: 0.0036 (SHAP: 0.007, FFA: 0.000)
  10. item_drug_ALLOPURINOL: 0.0028 (SHAP: 0.005, FFA: 0.000)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 744
  - Patients with consensus features: 744

================================================================================

2026-06-21 02:27:56,752 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

--> Step 8 (FFA + combine bin=high): ed / 65-74

2026-06-21 02:27:57,295 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:27:58,116 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:27:58,202 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/high/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:27:58,222 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/high/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:27:58,238 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/high/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:27:58,281 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 65-74 --workers 1 --bin high --upload-to-gold
2026-06-21 02:27:58,596 - INFO - Combining SHAP + FFA for ed/65-74 bin=high
2026-06-21 02:28:00,060 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:00,146 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/dashboard_data.json (skipping upload)
2026-06-21 02:28:00,158 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/combined_importance.csv (skipping upload)
2026-06-21 02:28:00,174 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/combined_shap_importance.csv (skipping upload)
2026-06-21 02:28:00,184 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/top_interaction_factors.csv (skipping upload)
2026-06-21 02:28:00,198 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/consensus_features.json (skipping upload)
2026-06-21 02:28:00,210 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/patient_explanations.csv (skipping upload)
2026-06-21 02:28:00,225 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/high/summary_report.txt (skipping upload)
2026-06-21 02:28:00,259 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/65_74/bin_models/high

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 25, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 20
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 100.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_ALPRAZOLAM: 0.1296 (SHAP: 0.211, FFA: 0.048)
  3. item_drug_CARVEDILOL: 0.0506 (SHAP: 0.092, FFA: 0.009)
  4. item_drug_IBUPROFEN: 0.0403 (SHAP: 0.073, FFA: 0.007)
  5. item_drug_METRONIDAZOLE: 0.0399 (SHAP: 0.072, FFA: 0.008)
  6. item_drug_AMOXICILLIN: 0.0394 (SHAP: 0.075, FFA: 0.004)
  7. item_drug_LEVOFLOXACIN: 0.0338 (SHAP: 0.063, FFA: 0.005)
  8. item_drug_PREDNISONE: 0.0237 (SHAP: 0.046, FFA: 0.002)
  9. item_drug_MELOXICAM: 0.0230 (SHAP: 0.044, FFA: 0.002)
  10. item_drug_ALLOPURINOL: 0.0211 (SHAP: 0.039, FFA: 0.003)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 1391
  - Patients with consensus features: 1391

================================================================================

2026-06-21 02:28:00,500 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/high
  Summary - found: ['high']  |  missing: (none)

--> Step 8 (FFA + combine bin=extreme): ed / 65-74

2026-06-21 02:28:01,046 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:28:01,868 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:01,954 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/extreme/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:28:01,968 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/extreme/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:28:01,982 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/65-74/bin_models/extreme/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:28:02,016 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 65-74 --workers 1 --bin extreme --upload-to-gold
2026-06-21 02:28:02,331 - INFO - Combining SHAP + FFA for ed/65-74 bin=extreme
2026-06-21 02:28:03,321 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:03,404 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/dashboard_data.json (skipping upload)
2026-06-21 02:28:03,422 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/combined_importance.csv (skipping upload)
2026-06-21 02:28:03,436 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/combined_shap_importance.csv (skipping upload)
2026-06-21 02:28:03,449 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/top_interaction_factors.csv (skipping upload)
2026-06-21 02:28:03,462 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/consensus_features.json (skipping upload)
2026-06-21 02:28:03,477 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/patient_explanations.csv (skipping upload)
2026-06-21 02:28:03,493 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/65-74/bin_models/extreme/summary_report.txt (skipping upload)
2026-06-21 02:28:03,527 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/65_74/bin_models/extreme

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 65-74
================================================================================

FEATURE TYPES (combined importance):
  drug: 15, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 16
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 80.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_CARVEDILOL: 0.3941 (SHAP: 0.585, FFA: 0.203)
  3. item_drug_LISINOPRIL: 0.2126 (SHAP: 0.353, FFA: 0.073)
  4. item_drug_LEVOFLOXACIN: 0.2092 (SHAP: 0.349, FFA: 0.069)
  5. item_drug_GABAPENTIN: 0.1457 (SHAP: 0.254, FFA: 0.037)
  6. item_drug_FUROSEMIDE: 0.1152 (SHAP: 0.199, FFA: 0.031)
  7. item_drug_PREDNISONE: 0.1150 (SHAP: 0.204, FFA: 0.026)
  8. item_drug_SIMVASTATIN: 0.0577 (SHAP: 0.107, FFA: 0.009)
  9. item_drug_LORAZEPAM: 0.0467 (SHAP: 0.087, FFA: 0.006)
  10. item_drug_CEPHALEXIN: 0.0158 (SHAP: 0.031, FFA: 0.001)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 245
  - Patients with consensus features: 245

================================================================================

2026-06-21 02:28:03,771 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 65-74 ===
  Canonical path: 6_final_model/outputs/ed/65_74/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/65_74/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

--> Step 8 (FFA + combine bin=low): ed / 75-84

2026-06-21 02:28:04,322 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:28:05,144 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:05,230 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/low/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:28:05,247 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/low/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:28:05,264 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/low/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:28:05,315 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 75-84 --workers 1 --bin low --upload-to-gold
2026-06-21 02:28:05,629 - INFO - Combining SHAP + FFA for ed/75-84 bin=low
2026-06-21 02:28:06,703 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:06,793 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/dashboard_data.json (skipping upload)
2026-06-21 02:28:06,808 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/combined_importance.csv (skipping upload)
2026-06-21 02:28:06,819 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/combined_shap_importance.csv (skipping upload)
2026-06-21 02:28:06,831 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/top_interaction_factors.csv (skipping upload)
2026-06-21 02:28:06,843 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/consensus_features.json (skipping upload)
2026-06-21 02:28:06,859 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/patient_explanations.csv (skipping upload)
2026-06-21 02:28:06,875 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/low/summary_report.txt (skipping upload)
2026-06-21 02:28:06,907 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/75_84/bin_models/low

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 12, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 13
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 65.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_CEPHALEXIN: 0.0452 (SHAP: 0.080, FFA: 0.010)
  3. item_drug_SIMVASTATIN: 0.0296 (SHAP: 0.054, FFA: 0.005)
  4. item_drug_LISINOPRIL: 0.0198 (SHAP: 0.034, FFA: 0.006)
  5. item_drug_OMEPRAZOLE: 0.0172 (SHAP: 0.032, FFA: 0.002)
  6. item_drug_AMOXICILLIN: 0.0122 (SHAP: 0.023, FFA: 0.001)
  7. item_drug_HYDROCHLOROTHIAZIDE: 0.0078 (SHAP: 0.015, FFA: 0.000)
  8. item_drug_ATENOLOL: 0.0046 (SHAP: 0.009, FFA: 0.000)
  9. item_drug_CARVEDILOL: 0.0036 (SHAP: 0.007, FFA: 0.000)
  10. item_drug_LATANOPROST: 0.0017 (SHAP: 0.003, FFA: 0.000)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 470
  - Patients with consensus features: 470

================================================================================

2026-06-21 02:28:07,148 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] low       /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/low
  Summary - found: ['low']  |  missing: (none)

--> Step 8 (FFA + combine bin=medium): ed / 75-84

2026-06-21 02:28:07,689 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:28:08,511 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:08,612 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/medium/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:28:08,623 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/medium/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:28:08,637 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/medium/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:28:08,666 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 75-84 --workers 1 --bin medium --upload-to-gold
2026-06-21 02:28:08,980 - INFO - Combining SHAP + FFA for ed/75-84 bin=medium
2026-06-21 02:28:09,945 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:10,027 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/dashboard_data.json (skipping upload)
2026-06-21 02:28:10,039 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/combined_importance.csv (skipping upload)
2026-06-21 02:28:10,057 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/combined_shap_importance.csv (skipping upload)
2026-06-21 02:28:10,084 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/top_interaction_factors.csv (skipping upload)
2026-06-21 02:28:10,094 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/consensus_features.json (skipping upload)
2026-06-21 02:28:10,106 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/patient_explanations.csv (skipping upload)
2026-06-21 02:28:10,121 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/medium/summary_report.txt (skipping upload)
2026-06-21 02:28:10,160 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/75_84/bin_models/medium

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 9, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 10
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 50.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_AZITHROMYCIN: 0.0515 (SHAP: 0.091, FFA: 0.012)
  3. item_drug_LISINOPRIL: 0.0393 (SHAP: 0.073, FFA: 0.006)
  4. item_drug_SIMVASTATIN: 0.0256 (SHAP: 0.048, FFA: 0.003)
  5. item_drug_CARVEDILOL: 0.0195 (SHAP: 0.037, FFA: 0.002)
  6. item_drug_LORAZEPAM: 0.0120 (SHAP: 0.023, FFA: 0.001)
  7. item_drug_OMEPRAZOLE: 0.0087 (SHAP: 0.017, FFA: 0.001)
  8. item_drug_CEPHALEXIN: 0.0031 (SHAP: 0.006, FFA: 0.000)
  9. item_drug_HYDROCHLOROTHIAZIDE: 0.0022 (SHAP: 0.004, FFA: 0.000)
  10. item_drug_AMOXICILLIN: 0.0000 (SHAP: 0.000, FFA: 0.000)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 181
  - Patients with consensus features: 181

================================================================================

2026-06-21 02:28:10,396 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] medium    /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/medium
  Summary - found: ['medium']  |  missing: (none)

--> Step 8 (FFA + combine bin=high): ed / 75-84

2026-06-21 02:28:10,934 - INFO - FFA outputs already exist locally; skipping FFA computation.
2026-06-21 02:28:11,756 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:11,851 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/high/xgboost/axp_explanations.parquet (skipping upload)
2026-06-21 02:28:11,872 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/high/xgboost/feature_importance_axp.parquet (skipping upload)
2026-06-21 02:28:11,925 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/high/ffa_causal_factors.csv (skipping upload)
2026-06-21 02:28:11,984 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 75-84 --workers 1 --bin high --upload-to-gold
2026-06-21 02:28:12,300 - INFO - Combining SHAP + FFA for ed/75-84 bin=high
2026-06-21 02:28:13,364 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:13,455 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/dashboard_data.json (skipping upload)
2026-06-21 02:28:13,468 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/combined_importance.csv (skipping upload)
2026-06-21 02:28:13,480 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/combined_shap_importance.csv (skipping upload)
2026-06-21 02:28:13,498 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/top_interaction_factors.csv (skipping upload)
2026-06-21 02:28:13,515 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/consensus_features.json (skipping upload)
2026-06-21 02:28:13,536 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/patient_explanations.csv (skipping upload)
2026-06-21 02:28:13,556 - INFO - [OK] File already exists in S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/high/summary_report.txt (skipping upload)
2026-06-21 02:28:13,593 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/75_84/bin_models/high

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 12, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 13
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 65.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_ELIQUIS: 0.1289 (SHAP: 0.207, FFA: 0.051)
  3. item_drug_HYDROCHLOROTHIAZIDE: 0.1095 (SHAP: 0.179, FFA: 0.040)
  4. item_drug_AZITHROMYCIN: 0.1026 (SHAP: 0.173, FFA: 0.033)
  5. item_drug_LORAZEPAM: 0.0683 (SHAP: 0.119, FFA: 0.017)
  6. item_drug_SIMVASTATIN: 0.0629 (SHAP: 0.111, FFA: 0.015)
  7. item_drug_CARVEDILOL: 0.0553 (SHAP: 0.099, FFA: 0.012)
  8. item_drug_CEPHALEXIN: 0.0451 (SHAP: 0.082, FFA: 0.008)
  9. item_drug_OMEPRAZOLE: 0.0440 (SHAP: 0.081, FFA: 0.007)
  10. item_drug_LATANOPROST: 0.0105 (SHAP: 0.020, FFA: 0.001)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 421
  - Patients with consensus features: 421

================================================================================

2026-06-21 02:28:13,839 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] high      /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/high
  Summary - found: ['high']  |  missing: (none)

--> Step 8 (FFA + combine bin=extreme): ed / 75-84

2026-06-21 02:28:15,214 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:15,301 - INFO - SHAP outputs already exist for ed/75-84 bin=extreme
2026-06-21 02:28:15,774 - INFO - Loading model JSON from: /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/extreme/final_model_json/ed_75_84_best_xgboost_model.json
2026-06-21 02:28:15,774 - INFO - Reading JSON file (size: 0.38 MB)...
2026-06-21 02:28:15,775 - INFO - JSON file loaded successfully in 0.00 seconds
2026-06-21 02:28:15,776 - INFO - Model type detected: xgboost_rf
2026-06-21 02:28:15,776 - INFO - Found 527 trees
2026-06-21 02:28:15,776 - INFO - Found 19 features
2026-06-21 02:28:15,776 - INFO - Model loading completed in 0.00 seconds
2026-06-21 02:28:15,776 - INFO - Extracting feature mappings from model JSON...
2026-06-21 02:28:15,776 - INFO - Processing XGBoost feature mappings...
2026-06-21 02:28:15,776 - INFO - Found 19 feature names
2026-06-21 02:28:15,776 - INFO - Feature mapping extraction completed in 0.00 seconds
2026-06-21 02:28:15,776 - INFO - Processing 527 trees from model JSON
2026-06-21 02:28:15,797 - INFO - Tree 1/527: Total rules so far: 40
2026-06-21 02:28:15,820 - INFO - Tree 2/527: Total rules so far: 94
2026-06-21 02:28:15,841 - INFO - Tree 3/527: Total rules so far: 141
2026-06-21 02:28:15,861 - INFO - Tree 4/527: Total rules so far: 188
2026-06-21 02:28:15,882 - INFO - Tree 5/527: Total rules so far: 237
2026-06-21 02:28:25,343 - INFO - Finished processing: 527/527 trees created rules, Total rules: 22236
2026-06-21 02:28:25,343 - INFO - Explainer fitted with 22236 rules
2026-06-21 02:28:25,389 - INFO - Computing rule frequencies across 73 instances...
2026-06-21 02:28:25,391 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,393 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 231, elapsed 0.00s
2026-06-21 02:28:25,394 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 452, elapsed 0.00s
2026-06-21 02:28:25,395 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 653, elapsed 0.01s
2026-06-21 02:28:25,396 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 899, elapsed 0.01s
2026-06-21 02:28:25,397 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1112, elapsed 0.01s
2026-06-21 02:28:25,398 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 1333, elapsed 0.01s
2026-06-21 02:28:25,399 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 1550, elapsed 0.01s
2026-06-21 02:28:25,400 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 1760, elapsed 0.01s
2026-06-21 02:28:25,401 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 1970, elapsed 0.01s
2026-06-21 02:28:25,402 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 2163, elapsed 0.01s
2026-06-21 02:28:25,413 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 4672, took 0.0240s
2026-06-21 02:28:25,414 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,415 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 366, elapsed 0.00s
2026-06-21 02:28:25,416 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 733, elapsed 0.00s
2026-06-21 02:28:25,417 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1097, elapsed 0.00s
2026-06-21 02:28:25,418 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1468, elapsed 0.00s
2026-06-21 02:28:25,419 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1832, elapsed 0.01s
2026-06-21 02:28:25,420 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2203, elapsed 0.01s
2026-06-21 02:28:25,421 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2577, elapsed 0.01s
2026-06-21 02:28:25,422 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2942, elapsed 0.01s
2026-06-21 02:28:25,423 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3308, elapsed 0.01s
2026-06-21 02:28:25,424 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3675, elapsed 0.01s
2026-06-21 02:28:25,434 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7699, took 0.0206s
2026-06-21 02:28:25,435 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,436 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 363, elapsed 0.00s
2026-06-21 02:28:25,437 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 732, elapsed 0.00s
2026-06-21 02:28:25,438 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1089, elapsed 0.00s
2026-06-21 02:28:25,439 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1462, elapsed 0.00s
2026-06-21 02:28:25,440 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1825, elapsed 0.01s
2026-06-21 02:28:25,441 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2194, elapsed 0.01s
2026-06-21 02:28:25,442 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2563, elapsed 0.01s
2026-06-21 02:28:25,443 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2932, elapsed 0.01s
2026-06-21 02:28:25,444 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3293, elapsed 0.01s
2026-06-21 02:28:25,445 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3655, elapsed 0.01s
2026-06-21 02:28:25,456 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7669, took 0.0206s
2026-06-21 02:28:25,456 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,457 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 388, elapsed 0.00s
2026-06-21 02:28:25,458 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 773, elapsed 0.00s
2026-06-21 02:28:25,459 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1143, elapsed 0.00s
2026-06-21 02:28:25,460 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1527, elapsed 0.00s
2026-06-21 02:28:25,461 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1904, elapsed 0.00s
2026-06-21 02:28:25,462 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2281, elapsed 0.01s
2026-06-21 02:28:25,463 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2660, elapsed 0.01s
2026-06-21 02:28:25,464 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 3038, elapsed 0.01s
2026-06-21 02:28:25,465 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3412, elapsed 0.01s
2026-06-21 02:28:25,466 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3781, elapsed 0.01s
2026-06-21 02:28:25,477 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7937, took 0.0202s
2026-06-21 02:28:25,477 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,478 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 366, elapsed 0.00s
2026-06-21 02:28:25,479 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 733, elapsed 0.00s
2026-06-21 02:28:25,480 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1097, elapsed 0.00s
2026-06-21 02:28:25,481 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1468, elapsed 0.00s
2026-06-21 02:28:25,482 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1832, elapsed 0.00s
2026-06-21 02:28:25,483 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2203, elapsed 0.01s
2026-06-21 02:28:25,484 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2577, elapsed 0.01s
2026-06-21 02:28:25,485 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2942, elapsed 0.01s
2026-06-21 02:28:25,486 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3308, elapsed 0.01s
2026-06-21 02:28:25,487 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3675, elapsed 0.01s
2026-06-21 02:28:25,497 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7699, took 0.0201s
2026-06-21 02:28:25,498 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,499 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 334, elapsed 0.00s
2026-06-21 02:28:25,500 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 662, elapsed 0.00s
2026-06-21 02:28:25,501 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 955, elapsed 0.00s
2026-06-21 02:28:25,502 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1292, elapsed 0.00s
2026-06-21 02:28:25,503 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1582, elapsed 0.00s
2026-06-21 02:28:25,504 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 1889, elapsed 0.01s
2026-06-21 02:28:25,505 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2210, elapsed 0.01s
2026-06-21 02:28:25,506 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2513, elapsed 0.01s
2026-06-21 02:28:25,507 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 2825, elapsed 0.01s
2026-06-21 02:28:25,507 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3111, elapsed 0.01s
2026-06-21 02:28:25,518 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 6592, took 0.0202s
2026-06-21 02:28:25,518 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,519 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 388, elapsed 0.00s
2026-06-21 02:28:25,520 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 773, elapsed 0.00s
2026-06-21 02:28:25,521 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1143, elapsed 0.00s
2026-06-21 02:28:25,522 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1527, elapsed 0.00s
2026-06-21 02:28:25,523 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1904, elapsed 0.00s
2026-06-21 02:28:25,524 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2281, elapsed 0.01s
2026-06-21 02:28:25,525 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2660, elapsed 0.01s
2026-06-21 02:28:25,526 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 3038, elapsed 0.01s
2026-06-21 02:28:25,527 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3412, elapsed 0.01s
2026-06-21 02:28:25,528 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3781, elapsed 0.01s
2026-06-21 02:28:25,538 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7937, took 0.0201s
2026-06-21 02:28:25,539 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,540 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 231, elapsed 0.00s
2026-06-21 02:28:25,541 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 452, elapsed 0.00s
2026-06-21 02:28:25,542 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 653, elapsed 0.00s
2026-06-21 02:28:25,543 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 899, elapsed 0.00s
2026-06-21 02:28:25,544 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1112, elapsed 0.00s
2026-06-21 02:28:25,545 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 1333, elapsed 0.01s
2026-06-21 02:28:25,546 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 1550, elapsed 0.01s
2026-06-21 02:28:25,547 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 1760, elapsed 0.01s
2026-06-21 02:28:25,548 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 1970, elapsed 0.01s
2026-06-21 02:28:25,549 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 2163, elapsed 0.01s
2026-06-21 02:28:25,559 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 4672, took 0.0205s
2026-06-21 02:28:25,560 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,561 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 363, elapsed 0.00s
2026-06-21 02:28:25,562 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 732, elapsed 0.00s
2026-06-21 02:28:25,563 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1089, elapsed 0.00s
2026-06-21 02:28:25,564 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1462, elapsed 0.00s
2026-06-21 02:28:25,565 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1825, elapsed 0.00s
2026-06-21 02:28:25,566 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2194, elapsed 0.01s
2026-06-21 02:28:25,567 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2563, elapsed 0.01s
2026-06-21 02:28:25,568 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2932, elapsed 0.01s
2026-06-21 02:28:25,568 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3293, elapsed 0.01s
2026-06-21 02:28:25,569 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3655, elapsed 0.01s
2026-06-21 02:28:25,580 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7669, took 0.0200s
2026-06-21 02:28:25,580 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,581 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 365, elapsed 0.00s
2026-06-21 02:28:25,582 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 728, elapsed 0.00s
2026-06-21 02:28:25,583 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1089, elapsed 0.00s
2026-06-21 02:28:25,584 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1461, elapsed 0.00s
2026-06-21 02:28:25,585 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1816, elapsed 0.00s
2026-06-21 02:28:25,586 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2181, elapsed 0.01s
2026-06-21 02:28:25,587 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2547, elapsed 0.01s
2026-06-21 02:28:25,588 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2902, elapsed 0.01s
2026-06-21 02:28:25,589 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3267, elapsed 0.01s
2026-06-21 02:28:25,590 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3624, elapsed 0.01s
2026-06-21 02:28:25,600 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7588, took 0.0201s
2026-06-21 02:28:25,601 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,602 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 366, elapsed 0.00s
2026-06-21 02:28:25,603 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 733, elapsed 0.00s
2026-06-21 02:28:25,604 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1097, elapsed 0.00s
2026-06-21 02:28:25,605 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1468, elapsed 0.00s
2026-06-21 02:28:25,606 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1832, elapsed 0.00s
2026-06-21 02:28:25,607 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2203, elapsed 0.01s
2026-06-21 02:28:25,608 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2577, elapsed 0.01s
2026-06-21 02:28:25,609 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2942, elapsed 0.01s
2026-06-21 02:28:25,610 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3308, elapsed 0.01s
2026-06-21 02:28:25,611 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3675, elapsed 0.01s
2026-06-21 02:28:25,621 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7699, took 0.0201s
2026-06-21 02:28:25,621 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,622 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 231, elapsed 0.00s
2026-06-21 02:28:25,623 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 452, elapsed 0.00s
2026-06-21 02:28:25,624 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 653, elapsed 0.00s
2026-06-21 02:28:25,625 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 899, elapsed 0.00s
2026-06-21 02:28:25,626 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1112, elapsed 0.01s
2026-06-21 02:28:25,627 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 1333, elapsed 0.01s
2026-06-21 02:28:25,628 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 1550, elapsed 0.01s
2026-06-21 02:28:25,629 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 1760, elapsed 0.01s
2026-06-21 02:28:25,630 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 1970, elapsed 0.01s
2026-06-21 02:28:25,631 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 2163, elapsed 0.01s
2026-06-21 02:28:25,642 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 4672, took 0.0207s
2026-06-21 02:28:25,642 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,643 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 366, elapsed 0.00s
2026-06-21 02:28:25,644 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 733, elapsed 0.00s
2026-06-21 02:28:25,645 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1097, elapsed 0.00s
2026-06-21 02:28:25,646 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1468, elapsed 0.00s
2026-06-21 02:28:25,647 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1832, elapsed 0.00s
2026-06-21 02:28:25,648 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2203, elapsed 0.01s
2026-06-21 02:28:25,649 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2577, elapsed 0.01s
2026-06-21 02:28:25,650 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2942, elapsed 0.01s
2026-06-21 02:28:25,651 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3308, elapsed 0.01s
2026-06-21 02:28:25,652 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3675, elapsed 0.01s
2026-06-21 02:28:25,663 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7699, took 0.0204s
2026-06-21 02:28:25,663 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,664 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 366, elapsed 0.00s
2026-06-21 02:28:25,665 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 733, elapsed 0.00s
2026-06-21 02:28:25,666 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1097, elapsed 0.00s
2026-06-21 02:28:25,667 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1468, elapsed 0.00s
2026-06-21 02:28:25,668 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1832, elapsed 0.00s
2026-06-21 02:28:25,669 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2203, elapsed 0.01s
2026-06-21 02:28:25,670 - INFO - _satisfied_rules: Checked 3500/10507 rules, matched 2577, elapsed 0.01s
2026-06-21 02:28:25,671 - INFO - _satisfied_rules: Checked 4000/10507 rules, matched 2942, elapsed 0.01s
2026-06-21 02:28:25,672 - INFO - _satisfied_rules: Checked 4500/10507 rules, matched 3308, elapsed 0.01s
2026-06-21 02:28:25,673 - INFO - _satisfied_rules: Checked 5000/10507 rules, matched 3675, elapsed 0.01s
2026-06-21 02:28:25,684 - INFO - _satisfied_rules: Completed - checked 10507 rules, matched 7699, took 0.0202s
2026-06-21 02:28:25,684 - INFO - _satisfied_rules: Starting check of 10507 rules for class 0
2026-06-21 02:28:25,685 - INFO - _satisfied_rules: Checked 500/10507 rules, matched 366, elapsed 0.00s
2026-06-21 02:28:25,686 - INFO - _satisfied_rules: Checked 1000/10507 rules, matched 733, elapsed 0.00s
2026-06-21 02:28:25,687 - INFO - _satisfied_rules: Checked 1500/10507 rules, matched 1097, elapsed 0.00s
2026-06-21 02:28:25,688 - INFO - _satisfied_rules: Checked 2000/10507 rules, matched 1468, elapsed 0.00s
2026-06-21 02:28:25,689 - INFO - _satisfied_rules: Checked 2500/10507 rules, matched 1832, elapsed 0.00s
2026-06-21 02:28:25,690 - INFO - _satisfied_rules: Checked 3000/10507 rules, matched 2203, elapsed 0.01s

=== Per-bin Step 6 output validation: ed / 75-84 ===
  Canonical path: 6_final_model/outputs/ed/75_84/bin_models/<bin>/
  [OK     ] extreme   /home/pgx3874/cpic_time_to_event_analysis/6_final_model/outputs/ed/75_84/bin_models/extreme
  Summary - found: ['extreme']  |  missing: (none)

Generating explanations:   0%|          | 0/73 [00:00<?, ?it/s]2026-06-21 02:28:27,099 - INFO - Completed 1/73 instances
2026-06-21 02:28:27,113 - INFO - Completed 2/73 instances
2026-06-21 02:28:27,119 - INFO - Completed 3/73 instances
2026-06-21 02:28:27,119 - INFO - Completed 4/73 instances
2026-06-21 02:28:27,120 - INFO - Completed 5/73 instances
Generating explanations:  63%|██████▎   | 46/73 [00:00<00:00, 87.70it/s] 2026-06-21 02:28:27,540 - INFO - Completed 50/73 instances
Generating explanations: 100%|██████████| 73/73 [00:00<00:00, 131.46it/s]
2026-06-21 02:28:27,736 - INFO - Wrote /home/pgx3874/cpic_time_to_event_analysis/8_ffa_analysis/outputs/ed/75_84/bin_models/extreme/xgboost/axp_explanations.parquet (73 rows)
2026-06-21 02:28:27,741 - INFO - Wrote FFA outputs under /home/pgx3874/cpic_time_to_event_analysis/8_ffa_analysis/outputs/ed/75_84/bin_models/extreme
2026-06-21 02:28:27,825 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/extreme/xgboost/axp_explanations.parquet
2026-06-21 02:28:27,866 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/extreme/xgboost/feature_importance_axp.parquet
2026-06-21 02:28:27,906 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/ffa_analysis/ed/75-84/bin_models/extreme/ffa_causal_factors.csv
2026-06-21 02:28:27,940 - INFO - Running combine step: /home/pgx3874/jupyter-env/bin/python3.11 /home/pgx3874/cpic_time_to_event_analysis/10_analysis_results/data_preparation/combine_shap_ffa_results.py --cohort ed --age-band 75-84 --workers 1 --bin extreme --upload-to-gold
2026-06-21 02:28:28,250 - INFO - Combining SHAP + FFA for ed/75-84 bin=extreme
2026-06-21 02:28:29,162 - INFO - Found credentials from IAM Role: EC2_Spot
2026-06-21 02:28:29,284 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/dashboard_data.json
2026-06-21 02:28:29,325 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/combined_importance.csv
2026-06-21 02:28:29,363 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/combined_shap_importance.csv
2026-06-21 02:28:29,401 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/top_interaction_factors.csv
2026-06-21 02:28:29,440 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/consensus_features.json
2026-06-21 02:28:29,482 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/patient_explanations.csv
2026-06-21 02:28:29,524 - INFO - [OK] Uploaded to S3: s3://pgxdatalake/gold/cpic_time_to_event/analysis_visuals/scenario/ed/75-84/bin_models/extreme/summary_report.txt
2026-06-21 02:28:29,548 - INFO - Wrote combined SHAP + FFA artifacts to 10_analysis_results/visualizations/scenario/ed/75_84/bin_models/extreme

================================================================================
SHAP + FFA COMBINED ANALYSIS SUMMARY
  Cohort: ed / 75-84
================================================================================

FEATURE TYPES (combined importance):
  drug: 9, icd: 0, cpt: 0, other: 1

CONSENSUS FEATURES:
  - Consensus features: 10
  - SHAP-only features: 0
  - FFA-only features: 0
  - Consensus rate: 50.0%

COMBINED FEATURE IMPORTANCE (Top 10):
  1. pgx_num_drugs: 1.0000 (SHAP: 1.000, FFA: 1.000)
  2. item_drug_AZITHROMYCIN: 0.1522 (SHAP: 0.269, FFA: 0.035)
  3. item_drug_LISINOPRIL: 0.0751 (SHAP: 0.139, FFA: 0.011)
  4. item_drug_CARVEDILOL: 0.0704 (SHAP: 0.133, FFA: 0.008)
  5. item_drug_SIMVASTATIN: 0.0488 (SHAP: 0.091, FFA: 0.006)
  6. item_drug_OMEPRAZOLE: 0.0360 (SHAP: 0.069, FFA: 0.003)
  7. item_drug_LORAZEPAM: 0.0335 (SHAP: 0.064, FFA: 0.003)
  8. item_drug_CEPHALEXIN: 0.0098 (SHAP: 0.019, FFA: 0.001)
  9. item_drug_HYDROCHLOROTHIAZIDE: 0.0035 (SHAP: 0.007, FFA: 0.000)
  10. item_drug_AMOXICILLIN: 0.0000 (SHAP: 0.000, FFA: 0.000)

PATIENT EXPLANATIONS:
  - Total patients analyzed: 73
  - Patients with consensus features: 73

================================================================================

2026-06-21 02:28:29,743 - INFO - Step 8 FFA + combined SHAP/FFA workflow complete.

Step 8 (FFA + combined SHAP/FFA artifacts) complete.

## Combined SHAP+FFA

The Step 8 workflow also writes combined interaction/scenario artifacts under `10_analysis_results/visualizations/scenario/{cohort}/{age_band}/` and mirrors project-scoped gold artifacts to S3 when configured.

### Top 20 Consensus Feature Importance

The final review and visualization of the top 20 consensus features is handled in `4_results_review.ipynb`, using the combined SHAP+FFA consensus importance artifacts generated here.

In [11]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from py_helpers.event_density_utils import (
    cohort_aggregate_final_model_has_artifacts,
    list_trained_density_bins,
)

COMBINED_ROOT = PROJECT_ROOT / "10_analysis_results" / "visualizations" / "scenario"
combined_status_rows = []
combined_frames = []

for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        ab_f = age_band.replace("-", "_")
        trained_bins = list_trained_density_bins(PROJECT_ROOT, cohort, age_band)
        bin_names = list(trained_bins)
        if not bin_names and cohort_aggregate_final_model_has_artifacts(PROJECT_ROOT, cohort, age_band):
            bin_names = [None]

        for bin_name in bin_names:
            scenario_dir = COMBINED_ROOT / cohort / ab_f
            label_bin = bin_name or "aggregate"
            if bin_name:
                scenario_dir = scenario_dir / "bin_models" / bin_name

            combined_path = scenario_dir / "combined_importance.csv"
            consensus_path = scenario_dir / "consensus_features.json"
            patient_path = scenario_dir / "patient_explanations.csv"
            dashboard_path = scenario_dir / "dashboard_data.json"

            combined_exists = combined_path.exists()
            consensus_exists = consensus_path.exists()
            combined_status_rows.append({
                "cohort": cohort,
                "age_band": age_band,
                "bin": label_bin,
                "combined_importance": combined_exists,
                "consensus_features": consensus_exists,
                "patient_explanations": patient_path.exists(),
                "dashboard_data": dashboard_path.exists(),
                "scenario_dir": str(scenario_dir.relative_to(PROJECT_ROOT)) if scenario_dir.exists() else str(scenario_dir),
            })

            if not combined_exists:
                continue

            df = pd.read_csv(combined_path)
            if df.empty or "feature" not in df.columns:
                continue

            consensus_features = []
            if consensus_exists:
                with open(consensus_path, "r", encoding="utf-8") as f:
                    consensus_features = json.load(f).get("consensus_features", [])
            if consensus_features:
                df = df[df["feature"].astype(str).isin(set(map(str, consensus_features)))].copy()
            else:
                df = df.copy()
                df["consensus_warning"] = "consensus_features.json missing or empty; showing combined importance"

            df["cohort"] = cohort
            df["age_band"] = age_band
            df["bin"] = label_bin
            combined_frames.append(df)

combined_status = pd.DataFrame(combined_status_rows)
print("Combined SHAP+FFA artifact coverage:")
display(combined_status)

if combined_frames:
    combined_consensus_importance = pd.concat(combined_frames, ignore_index=True)
    combined_consensus_importance = combined_consensus_importance.sort_values(
        ["cohort", "age_band", "bin", "combined_importance", "feature"],
        ascending=[True, True, True, False, True],
    )
    top20_consensus_by_bin = (
        combined_consensus_importance
        .groupby(["cohort", "age_band", "bin"], as_index=False, group_keys=False)
        .head(20)
        .copy()
    )
    print("Top 20 Consensus Feature Importance per cohort / age band / bin:")
    print(f"Rows shown in heatmap input: {len(top20_consensus_by_bin):,}")

    heat = top20_consensus_by_bin.copy()
    heat["panel"] = heat["cohort"] + " / " + heat["age_band"] + " / " + heat["bin"].astype(str)
    feature_order = (
        heat.groupby("feature")["combined_importance"]
        .max()
        .sort_values(ascending=False)
        .index
    )
    mat = (
        heat.pivot_table(
            index="feature",
            columns="panel",
            values="combined_importance",
            aggfunc="max",
            fill_value=0,
        )
        .reindex(feature_order)
    )
    plt.figure(figsize=(max(10, 0.9 * mat.shape[1]), max(8, 0.28 * mat.shape[0])))
    sns.heatmap(mat, cmap="viridis", linewidths=0.2, linecolor="white")
    plt.title("Top 20 Consensus Feature Importance per Cohort / Bin")
    plt.xlabel("Cohort / age band / bin")
    plt.ylabel("Consensus feature")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()
else:
    combined_consensus_importance = pd.DataFrame()
    top20_consensus_by_bin = pd.DataFrame()
    print("No combined SHAP+FFA artifacts found yet. Run the FFA Analysis cell above.")

Combined SHAP+FFA artifact coverage:

,cohort,age_band,bin,combined_importance,consensus_features,patient_explanations,dashboard_data,scenario_dir
0,falls,65-74,low,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
1,falls,65-74,medium,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
2,falls,65-74,high,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
3,falls,65-74,extreme,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
4,falls,75-84,low,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
5,falls,75-84,medium,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
6,falls,75-84,high,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
7,falls,75-84,extreme,True,True,True,True,10_analysis_results/visualizations/scenario/fa...
8,ed,65-74,low,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
9,ed,65-74,medium,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
10,ed,65-74,high,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
11,ed,65-74,extreme,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
12,ed,75-84,low,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
13,ed,75-84,medium,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
14,ed,75-84,high,True,True,True,True,10_analysis_results/visualizations/scenario/ed...
15,ed,75-84,extreme,True,True,True,True,10_analysis_results/visualizations/scenario/ed...

Top 20 Consensus Feature Importance:

,cohort,age_band,bin,feature,combined_importance,shap_norm,ffa_norm
207,ed,75-84,low,pgx_num_drugs,1.0,1.0,1.0
143,ed,65-74,low,pgx_num_drugs,1.0,1.0,1.0
151,ed,65-74,medium,pgx_num_drugs,1.0,1.0,1.0
220,ed,75-84,medium,pgx_num_drugs,1.0,1.0,1.0
243,ed,75-84,extreme,pgx_num_drugs,1.0,1.0,1.0
...,...,...,...,...,...,...,...
242,ed,75-84,high,item_drug_AMOXICILLIN,0.0,0.0,0.0
219,ed,75-84,low,item_drug_ELIQUIS,0.0,0.0,0.0
206,ed,65-74,extreme,item_drug_ALPRAZOLAM,0.0,0.0,0.0
150,ed,65-74,low,item_drug_OMEPRAZOLE,0.0,0.0,0.0
229,ed,75-84,medium,item_drug_AMOXICILLIN,0.0,0.0,0.0

## Model Performance Per Density Bin

### Model Performance Summary

Run last in notebook 3 to confirm output files exist and check the selected model metrics per density bin.

In [12]:
import pandas as pd
from py_helpers.event_density_utils import DENSITY_BINS as _DENSITY_BINS

def _outputs_base():
    for base in (FINAL_MODEL_OUTPUTS, FINAL_MODEL_OUTPUTS_ALT):
        if base and base.exists():
            return base
    return FINAL_MODEL_OUTPUTS

base = _outputs_base()
print("Final model performance - per density bin")
print("=" * 80)
all_metrics = []
for cohort, bands in REQUIRED_COHORTS.items():
    for age_band in bands:
        ab_f = age_band.replace("-", "_")
        for bin_name in _DENSITY_BINS:
            path = (
                base / cohort / ab_f / "bin_models" / bin_name
                / f"{cohort}_{ab_f}_model_metrics_summary.csv"
            )
            if not path.exists():
                continue
            df = pd.read_csv(path)
            selected = df.loc[df["selected"] == True]
            if selected.empty:
                selected = df.head(1)
            for _, row in selected.iterrows():
                all_metrics.append({
                    "cohort": cohort,
                    "age_band": age_band,
                    "bin": bin_name,
                    "model": row["model"],
                    "recall_mean": row["recall_mean"],
                    "pr_auc_mean": row["pr_auc_mean"],
                    "auc_mean": row.get("auc_mean"),
                })
if all_metrics:
    print(pd.DataFrame(all_metrics).to_string(index=False))
else:
    print(f"  No metrics CSVs found under {base}")

Final model performance - per density bin
================================================================================
cohort age_band     bin      model  recall_mean  pr_auc_mean  auc_mean
 falls    65-74     low   Ensemble     0.758644     0.835849  0.827569
 falls    65-74  medium   Ensemble     0.689032     0.891589  0.919105
 falls    65-74    high   Ensemble     0.261818     0.712785  0.918206
 falls    65-74 extreme   Ensemble     0.689032     0.891589  0.919105
 falls    75-84     low   Ensemble     0.831282     0.867491  0.867515
 falls    75-84  medium   Ensemble     0.657647     0.832361  0.901846
 falls    75-84    high   Ensemble     0.028571     0.343226  0.781934
 falls    75-84 extreme   Ensemble     0.657647     0.832361  0.901846
    ed    65-74     low    XGBoost     0.972161     0.925475  0.896069
    ed    65-74  medium XGBoost_RF     0.520000     0.506887  0.873227
    ed    65-74    high XGBoost_RF     0.000000     0.075566  0.676651
    ed    65-74 extreme   CatBoost     0.000000     0.106837  0.510029
    ed    75-84     low    XGBoost     0.968800     0.960666  0.936429
    ed    75-84  medium XGBoost_RF     0.276000     0.432047  0.766444
    ed    75-84    high XGBoost_RF     0.000000     0.162271  0.653319
    ed    75-84 extreme XGBoost_RF     0.276000     0.432047  0.766444

## Notebook 3 Complete

Run `4_results_review.ipynb` next for the final results review, results artifact sync, and optional EC2 shutdown.

In [ ]:
print("Notebook 3 complete. Run 4_results_review.ipynb for final review, S3 sync, and optional EC2 shutdown.")

In [ ]:
# Spacer intentionally left blank.